### ISSUE TITLE
Consider cleaning up signature formatting

### ISSUE THREAD

**Issue by madelson** [Doraku/DefaultDocumentation#121]
I feel that the member signatures generated by the tool could be cleaned up a bit (e.g. in [this file](https://github.com/madelson/DistributedLock/blob/default-documentation/docs/api/DistributedLock.Azure/AzureBlobLeaseDistributedLock.AcquireAsync.ulCFSvmk3VUn6f5ebzKW9A.md)).

Primarily:
* It would be nice to use `T?` syntax rather than `System.Nullable<T>` for nullable value types
* It would be nice to have spacing around `=` for parameter default values
* It would be nice to use `= default` instead of `= default(T)` for value type default values

Thoughts? If you agree, I'd be happy to work on a PR.

**Comment by Doraku** [comment]
hum the definition of a member use [ICSharpCode.Decompiler](https://github.com/icsharpcode/ILSpy) to be written, I am not sure this is something easily changeable. It should at least be easier to clean the `System.Nullable<T> > T?` in [type links](https://github.com/Doraku/DefaultDocumentation/blob/master/source/DefaultDocumentation.Markdown/Extensions/IWriterExtension.cs#L158).

**Comment by Doraku** [comment]
Sorry for the long absence, looking back at this issue since the definition is completely in the hand of the ICsharpCode.Decompiler library, I feel like changing the types from `System.Nullable<T>` to `T?` could create confusion if the definition and the parameters do not use the same representation (even more so with the nullable annotation) so I think it will stay as is. I hope you understand 😉
