### ISSUE TITLE
Option to remove the upper-level link to the index document

### ISSUE THREAD

**Issue by nxrighthere** [Doraku/DefaultDocumentation#13]
Hey! First of all, thank you for the very useful package, I really like it. 👍⚡️ 

Would like to request an option to eliminate the upper-level link to the index document across the documentation. In my case, I have only one namespace which matches the name of a project and assembly, so it looks like this:

![x](https://user-images.githubusercontent.com/8279330/76157252-0d6c2a00-6128-11ea-9e8e-371bbe57a58d.PNG)

And on lower-level pages:

![v](https://user-images.githubusercontent.com/8279330/76157272-3d1b3200-6128-11ea-84f1-b091f4686953.PNG)

I just want to squeeze some space by eliminating it from there.

Also, please consider to upgrade the package to .NET Core 3 since the 2nd version is an end-on-life product today, so would be nice to not keep both runtimes installed in order to use the package.

Thanks!

**Comment by Doraku** [comment]
Great to know it suits you :)
You are right about netcore, too bad major revisions are not retro-compatible like netframework ones, I will see if it's better to just change the core version or make the .targets detect the version installed and use the correct dll accordingly.
I am not too fond of adding too many options but I can see that it is completely superfluous in your case. Normally this would be taken care by #4 but since I have still no solution in sight ^^" Maybe I can detect if you only have one namespace in your documentation and remove the home page if so? I think it makes sense in this case.

**Comment by nxrighthere** [comment]
> Maybe I can detect if you only have one namespace in your documentation and remove the home page if so? I think it makes sense in this case.

Absolutely, this sounds great.

**Comment by nxrighthere** [comment]
Nice, thanks!
