### ISSUE TITLE
add language type to markdown when using code tag

### ISSUE THREAD

**Issue by TroySi** [Doraku/DefaultDocumentation#23]
Is it possible to add the language type when using the code tag.  In my case I have a code tag inside an example tag and I would like the content inside the code tag to be marked as csharp.

Also, this is the best output from any of the documentation tools I've tried so far.

**Comment by Doraku** [comment]
Oh that's a big oversight on my part, definitely something that should have been there from the start! Thanks for bringing it up.

Many thanks for the praise, don't hesitate if you feel other stuff could be improved :)

**Comment by TroySi** [comment]
Thanks for adding that in there, works great.  Is it possible to use this as a dotnet tool?  I don't know much about how that works but I'm looking to try and use this on several projects and would like to have one instance of this tool installed.

**Comment by Doraku** [comment]
Since it is nothing but a simple command line tool it should be possible. From a quick test it is as simple as adding those two lines in the csproj
```
<PackAsTool>true</PackAsTool>
<ToolCommandName>defaultdocumentation</ToolCommandName>
```
but I have to disable the netframework target or it complains, and I don't know if the nuget is still compatible with the .target added post compilation to automatically generate the documentation on build if you wish to keep using it that way.
I will have to run some tests to see how it behaves, maybe create a new nuget specifically for the tool?
I will create a new issue for this.

Just so you know, even if the nuget is used by multiple projects, it will actually only be on your machine at one place, here `%USERPROFILE%\.nuget\packages\defaultdocumentation` while the dotnet tool would end up here `%USERPROFILE%\.dotnet\tools\.store\defaultdocumentation`
