### ISSUE TITLE
Add a setting to turn off DefaultDocumentation independently

### ISSUE THREAD

**Issue by Ellpeck** [Doraku/DefaultDocumentation#37]
It would be useful to have a setting to disable DefaultDocumentation even if `GenerateDocumentationFile` is enabled. For example, it's useful to have `GenerateDocumentationFile` enabled to see which methods don't have documentation yet (since enabling it also enables [CS1591](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1591)), but you don't necessarily want the documentation to be converted to markdown on every build.

By the way, thanks so much for this tool, it's really useful and by far the best one I've found for this purpose.

**Comment by Doraku** [comment]
Personally I use a custom condition in my csproj on the PackageReference to activate or deactivate the documentation generation:
```
<PackageReference Include="DefaultDocumentation" Version="0.6.13" PrivateAssets="all" Condition="'$(GENERATE_DEFAULT_DOCUMENTATION)' == 'true'" />
```
I think it makes more sense to either include or not DefaultDocumentation package reference if you want to generate the documentation rather than referencing the package and asking it to do nothing, what do you think?

> By the way, thanks so much for this tool, it's really useful and by far the best one I've found for this purpose.

Thanks, it is still missing some big feature (cross documentation reference) and I haven't given it some love for some time but I will get there eventually ^^

**Comment by Ellpeck** [comment]
You're right, that makes sense! I'll close this issue, then.

**Comment by Ellpeck** [comment]
Actually, on second thought: Doing it this way would require a `dotnet restore` every time the configuration changes, and while I think that `dotnet build` also restores every time, my testing has shown that IDEs like Rider and Visual studio *don't* restore packages every time you build in them. That means that this way of doing it wouldn't work there.

**Comment by Doraku** [comment]
hum I can see VS screwing things up with packages now then, it doesn't hurt to add a `DisableDefaultDocumentation` variable check in the target, will do.
