### ISSUE TITLE
Add support for code examples from actual code

### ISSUE THREAD

**Issue by basvanderlaken** [Doraku/DefaultDocumentation#40]
This can be done by using the extended C# XML comments as shown on [https://ewsoftware.github.io/XMLCommentsGuide/html/1abd1992-e3d0-45b4-b43d-91fcfc5e5574.htm].

I have a branch with this functionality added. If you would allow me to create a pull request I can push it.

**Comment by Doraku** [comment]
You should be able to create pull requests if you fork this repo :)
Since normally [`<code>`](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/code) elements are already supported, are you specifically talking about the attributes from Sandcastle? (language/source/...) It looks like a great addition indeed to not pollute actual code with example code.

**Comment by basvanderlaken** [comment]
Yes, I'm referring to the Sandcastle extension, although I thought these were originally extensions from Microsoft.

I've created the pull-request. In order for it to work, I had to update to .net5.0 due to version conflicts. with System.Reflection.Metadata

**Comment by Doraku** [comment]
I hope that's ok with you I decided to remove the Microsoft.CodeAnalysis.CSharp dependencies as it multiplied the packages size by 5-6 just for the code extraction. I redid the CodeRegion in this [commit](6a551e3fc482ff8adedf4031cc72cd370b3a5038) with regex (hopefully without error). The overall code should also be much more cleaner and easier to add new stuff too now.

**Comment by basvanderlaken** [comment]
That's great. My regex skills are horrible, so I thought it be best to solve this using the CSharp library.
