### ISSUE TITLE
Document generation have become significantly slower

### ISSUE THREAD

**Issue by cheeeeeeeeeen** [Doraku/DefaultDocumentation#58]
I used to use `0.6.12` for my projects, but after I updated to `0.7.4`, the generation has become *really* slow. I confirmed this by going back to the previous version of `0.6.12` and the generation as of this version is really fast.

~~Going to `0.6.15` and the slow down is also there, albeit it's still faster than `0.7.4`.~~ Untrue, tested again after restarting Visual Studio.

**Comment by Doraku** [comment]
Hey, I believe this is mainly linked to the strategy used to ensure previous documentation files are correctly deleted. I actually changed it because I experienced the same thing after upgrading (for some reason this doesn't occur with the dotnet tool version which is what I use to debug :/) but never released a version with the fix >_> (wanted to finish other stuff before)
version 0.7.5 should be available soon once nuget.org is done indexing, can you try with this one if it is back to acceptable time?

**Comment by cheeeeeeeeeen** [comment]
Yes. I will try. The newer feature of removing `.md` in links will be very useful to me.

**Comment by cheeeeeeeeeen** [comment]
@Doraku It's now fast! Thanks a bunch. Closing this issue. **For those looking for a solution, Just update to `0.7.5`.**
